### PR TITLE
Closing issue #18 and fixing not raising exception on running API

### PR DESCRIPTION
**Pull request by spookyahell**

### CODE REVIEW

**Comment by rosineygp** [comment]
there is some small erros, but I will try to fix here..

nice feature, thanks!!!!

**Comment by rosineygp** [comment]
https://github.com/rosineygp/PyIsEven/actions/runs/1099432163

**Comment by spookyahell** [comment]
> https://github.com/rosineygp/PyIsEven/actions/runs/1099432163

regarding 2.7 btw.. probably time to start dropping support for it...
`DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020.
Please upgrade your Python as Python 2.7 is no longer maintained.
pip 21.0 will drop support for Python 2.7 in January 2021.`

**Comment by spookyahell** [comment]
</img>
Took a (bit more than a) full hour, but now all issues are resolved.

This can be reviewed here: https://github.com/spookyahell/PyIsEven/actions/runs/1099593446

**Pull request merged**
