### PR TITLE
Fix support for Python 2

### PR DESCRIPTION
**Pull request by NCPlayz**

### CODE REVIEW

**Comment by rosineygp** [comment]
nice change!!!

but we need to improve the tests, I will try to fix it before merging

**Comment by NCPlayz** [comment]
Any updates? Looking forward to getting support on Python 2!

**Comment by rosineygp** [comment]
> Any updates? Looking forward to getting support on Python 2!

I am working here...

https://github.com/rosineygp/PyIsEven/tree/python-2-fix

I don't know how to patch a patch :(
This week I will try to finish it ;)

**Comment by NCPlayz** [comment]
Ah. Didn't see the branch! 🚀

**Pull request merged**
